# Basic Phyton codes

- Print
- Type
- Converting types
- Rounded division
- Operations with strings
- Tuples
- Lists
- Sets
- If
- Range
- Loop
- Functions

### Print

In [1]:
print('Hello, Python!')

Hello, Python!

### Type

In [5]:
type(2.14)

float

In [6]:
type('example')

str

In [7]:
type(5)

int

In [13]:
type(True)

bool

### Converting types

In [10]:
x=float(5)
type(x)

float

In [11]:
y=int('1')
type(y)

int

In [12]:
z=str(1.2)
type(z)

str

In [14]:
bool(1)

True

### Rounded Division

In [15]:
25//6

4

### Operations with Strings

In [16]:
Name='Example Example'

In [17]:
Name[0]

'E'

In [18]:
Name[10]

'a'

In [19]:
Name[-1]

'e'

In [20]:
len(Name)

15

In [21]:
Name[0:4]

'Exam'

In [22]:
Name[::2]

'EapeEape'

In [23]:
Name[0:5:2]

'Eap'

In [25]:
Name2=' Junior'
Name+Name2

'Example Example Junior'

In [26]:
2*Name2

' Junior Junior'

In [27]:
Name.upper()

'EXAMPLE EXAMPLE'

In [31]:
Name.replace('Ex','ix')

'ixample ixample'

In [33]:
Name.find('le') # hanyadik karaktertől kezdődik

5

### Tuples

In [42]:
tuple1=('example', 10, 1.3)
tuple1

('example', 10, 1.3)

In [37]:
type(tuple1)

tuple

In [38]:
tuple[1]

10

In [39]:
tuple[-1]

1.3

In [48]:
tuple2=('y','x')
tuple1+tuple2

('example', 10, 1.3, 'y', 'x')

In [44]:
tuple1[0:2]

('example', 10)

In [45]:
len(tuple1)

3

In [49]:
sorted(tuple2)

['x', 'y']

In [52]:
tuple3=(1,2,tuple1,tuple2)
tuple3

(1, 2, ('example', 10, 1.3), ('y', 'x'))

In [53]:
tuple3[2][0]

'example'

### Lists

In [60]:
List=['Example',10,1.3]
List

['Example', 10, 1.3]

#### Same operations can be used as for tuples, but list can be changed tuples don't

In [61]:
List.append(['x',21]) #immediatly impacts the list 
List

['Example', 10, 1.3, ['x', 21]]

In [62]:
List.extend(['x',21])

In [63]:
List

['Example', 10, 1.3, ['x', 21], 'x', 21]

In [64]:
del(List[0])
List

[10, 1.3, ['x', 21], 'x', 21]

In [66]:
'exa mple'.split() # result is list

['exa', 'mple']

In [70]:
a='A,B,C,D'.split(',')
a

['A', 'B', 'C', 'D']

#### Dictonaties are like lists, but instead of indexes, they have unique keys

### Sets

In [68]:
set1={'x','y','z','x','y','a'} # removes duplicates
set1

{'a', 'x', 'y', 'z'}

In [72]:
set2=set(a)
set2

{'A', 'B', 'C', 'D'}

In [73]:
set1.add('A')
set1

{'A', 'a', 'x', 'y', 'z'}

In [74]:
set1.remove('a')
set1

{'A', 'x', 'y', 'z'}

In [75]:
'A' in set1

True

In [76]:
set1 & set2

{'A'}

In [77]:
set1.difference(set2)

{'x', 'y', 'z'}

In [78]:
set1.intersection(set2)

{'A'}

In [79]:
set1.union(set2)

{'A', 'B', 'C', 'D', 'x', 'y', 'z'}

In [80]:
set1.issubset(set2)

False

In [81]:
set1.issuperset(set2)

False

### If Statement

In [85]:
x=20
if x !=19:
    print ('ok')
else:
    print ('no')

ok

In [89]:
x=5
if x>6:
    print ('a')
elif x==5:
    print ('b')
else:
    print ('c')

b

### Range

In [90]:
range(3) # 0,1,2

range(0, 3)

### Loop

In [91]:
example=[1,5,6,'x']
n=len(example)

for i in range(n):
    print(example[i])

1
5
6
x

In [92]:
for i in range(0, 8):
    print(i)

0
1
2
3
4
5
6
7

In [93]:
dates = [1982, 1980, 1973, 2000]

i = 0
year = 0

while(year != 1973):
    year = dates[i]
    i = i + 1
    print(year)

1982
1980
1973

### Functions

In [94]:
def add(a):
    b = a + 1
    return(b)

In [95]:
add(1)

2

In [96]:
help(add)

Help on function add in module __main__:

add(a)

In [97]:
def Mult(a, b):
    c = a * b
    return(c)

In [98]:
Mult(3,12)

36